<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <ProjectReference Include="..\rebalancer.Domain\rebalancer.Domain.csproj" />
    <ProjectReference Include="..\rebalancer.Infrastructure\rebalancer.Infrastructure.csproj" />
  </ItemGroup>

</Project>
