version: '3.8'
services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    working_dir: /app
    command: /bin/bash -c "dotnet restore && dotnet watch --project rebalancer.API/rebalancer.API.csproj run --no-restore"
    volumes:
      - /Users/charlesking/Development/rebalancer/src/backend:/app
    ports:
      - 5000:80
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true

  tests:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    working_dir: /app
    command: /bin/bash -c "dotnet restore && dotnet watch --project UnitTests/UnitTests.csproj test --no-restore"
    volumes:
      - /Users/charlesking/Development/rebalancer/src/backend:/app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true

  frontend:
    build: ./frontend/rebalancer-app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/rebalancer-app:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rebalancer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: