version: '3.8'
services:
  backend:
    build: ./backend/rebalancer.API
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend/rebalancer-app
    command: npm start
    ports:
      - "3000:3000"