services:
  backend:
    image: ghcr.io/cking27/rebalancer-backend:latest
    restart: unless-stopped
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=rebalancer;Username=postgres;Password=${POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rebalancer
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: ghcr.io/cking27/rebalancer-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    depends_on:
      - backend

volumes:
  postgres_data:
